import re
from bs4 import BeautifulSoup
import os
import sys

# === 配置区域 ===
# V11 更新：使用用户上传的新文件
INPUT_FILE = 'bookmarks_2025_11_21.html'
OUTPUT_FILE = 'index.html'

# 网页模板 (保持美观的样式和功能)
HTML_HEADER = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>我的个人导航</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🧭</text></svg>">
    <style>
        :root { --primary: #3b82f6; --bg-page: #f3f4f6; --bg-sidebar: #ffffff; --text-main: #1f2937; }
        body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg-page); color: var(--text-main); display: flex; height: 100vh; overflow: hidden; }
        .sidebar { width: 240px; background: var(--bg-sidebar); border-right: 1px solid #e5e7eb; display: flex; flex-direction: column; flex-shrink: 0; z-index: 20; }
        .logo { padding: 20px; font-size: 18px; font-weight: bold; color: var(--primary); border-bottom: 1px solid #eee; text-align: center; }
        .nav-scroll { flex: 1; overflow-y: auto; padding: 10px 0; }
        .nav-link { display: block; padding: 10px 20px; color: #4b5563; text-decoration: none; transition: 0.2s; font-size: 14px; border-left: 3px solid transparent; }
        .nav-link:hover, .nav-link.active { background: #eff6ff; color: var(--primary); border-left-color: var(--primary); font-weight: 500; }
        .main { flex: 1; overflow-y: auto; padding: 30px 40px; position: relative; }
        .search-box { max-width: 600px; margin: 0 auto 30px; }
        .search-input { width: 100%; padding: 15px 20px; border-radius: 50px; border: 1px solid #e5e7eb; outline: none; font-size: 16px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
        .category { margin-bottom: 40px; scroll-margin-top: 100px; }
        .cat-head { font-size: 18px; font-weight: 600; margin-bottom: 15px; padding-bottom: 8px; border-bottom: 1px dashed #ccc; color: #374151; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 15px; }
        .card { background: white; padding: 12px; border-radius: 8px; display: flex; align-items: center; text-decoration: none; transition: 0.2s; box-shadow: 0 1px 2px rgba(0,0,0,0.05); border: 1px solid transparent; }
        .card:hover { transform: translateY(-2px); box-shadow: 0 8px 16px rgba(0,0,0,0.1); border-color: var(--primary); }
        .card-icon { width: 32px; height: 32px; margin-right: 12px; border-radius: 50%; background: #f3f4f6; object-fit: cover; flex-shrink: 0; }
        .card-info { overflow: hidden; }
        .card-text { font-size: 14px; font-weight: 500; color: #111; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; margin-bottom: 2px; }
        .card-url { font-size: 12px; color: #9ca3af; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .scroll-to-top { position: fixed; bottom: 20px; right: 20px; background: var(--primary); color: white; border: none; padding: 10px 15px; border-radius: 5px; cursor: pointer; z-index: 100; opacity: 0.8; transition: opacity 0.3s; }
        .scroll-to-top:hover { opacity: 1; }
        @media (max-width: 768px) {
            .sidebar { width: 100%; height: auto; border-right: none; border-bottom: 1px solid #e5e7eb; position: static; overflow: visible; }
            .main { margin-left: 0; padding: 20px; }
            .grid { grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); }
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <div class="logo">我的导航</div>
        <div class="nav-scroll" id="nav-container"></div>
    </div>
    <div class="main">
        <div class="search-box">
            <input type="text" class="search-input" placeholder="输入关键词搜索书签，或回车搜索 Google..." id="searchInput">
        </div>
        <div id="content-container"></div>
        <footer style="text-align: center; margin-top: 50px; color: #9ca3af; font-size: 13px; padding-bottom: 20px;">
            Generated by Python Script | Last Update: <span id="date-now"></span>
        </footer>
    </div>
    <button class="scroll-to-top" onclick="window.scrollTo({ top: 0, behavior: 'smooth' })">TOP</button>

    <script>
        // 设置日期
        document.getElementById('date-now').innerText = new Date().toLocaleDateString();

        // 搜索功能
        const searchInput = document.getElementById('searchInput');
        const cards = document.getElementsByClassName('card');

        searchInput.addEventListener('keyup', function(e) {
            const term = e.target.value.toLowerCase();
            if (e.key === 'Enter' && term) {
                window.open('https://www.google.com/search?q=' + encodeURIComponent(term), '_blank');
                return;
            }
            for (let card of cards) {
                const text = card.innerText.toLowerCase();
                if (text.includes(term)) {
                    card.style.display = "flex";
                } else {
                    card.style.display = "none";
                }
            }
            document.querySelectorAll('.category').forEach(cat => {
                const visibleCards = cat.querySelectorAll('.card[style="display: flex;"]');
                cat.style.display = visibleCards.length > 0 ? 'block' : 'none';
            });
        });

        // 侧边栏链接点击跳转
        document.querySelectorAll('.nav-link').forEach(link => {
            link.addEventListener('click', function(e) {
                e.preventDefault();
                document.getElementById(this.getAttribute('href').substring(1)).scrollIntoView({ behavior: 'smooth' });
            });
        });
    </script>
</body>
</html>
"""


def create_link_data(link_tag):
    """从 BeautifulSoup <a> 标签中提取链接信息 (忽略 Base64 图标)"""
    title = link_tag.text.strip()
    if not title: return None

    # 使用统一的图标生成服务，避免 Base64 内存问题
    icon = f"https://ui-avatars.com/api/?background=random&color=fff&name={title[0] if title else 'X'}&size=64"

    return {
        'title': title,
        'url': link_tag.get('href', '#'),
        'icon': icon
    }


def parse_bookmarks():
    """解析书签文件并返回结构化数据"""
    if not os.path.exists(INPUT_FILE):
        print(f"❌ 错误：找不到文件 {INPUT_FILE}")
        return {}

    # 1. 尝试使用不同的编码读取文件
    content = ""
    for encoding in ['utf-8', 'gb18030', 'gbk']:
        try:
            with open(INPUT_FILE, 'r', encoding=encoding) as f:
                content = f.read()
            print(f"✅ 成功使用 {encoding} 编码读取文件")
            break
        except UnicodeDecodeError:
            continue

    if not content:
        print("❌ 无法读取文件内容")
        return {}

    # 2. V11 核心：使用 lxml 解析器进行线性扫描
    try:
        soup = BeautifulSoup(content, 'lxml')
    except Exception as e:
        print(f"❌ 使用 lxml 解析器时出错: {e}")
        return {}

    all_links = soup.find_all('a')
    print(f"🔍 调试：共扫描到 {len(all_links)} 个链接标签")

    if len(all_links) < 1:
        print("❌ 解析失败或文件内容为空。请检查书签文件！")
        return {}

    data = {}

    for link in all_links:
        link_data = create_link_data(link)
        if not link_data: continue

        # 查找分类：向上找最近的一个 H3 标签
        category = "未分类"
        header = link.find_previous('h3')
        if header:
            cat_text = header.text.strip()
            # 过滤掉顶层的“书签栏”或“Bookmarks”等字样
            if cat_text not in ["书签栏", "Bookmarks bar", "Bookmarks",
                                "Bookmarks Bar"]:
                category = cat_text

        # 添加到数据字典
        if category not in data:
            data[category] = []

        data[category].append(link_data)

    # 3. 组织最终数据 (确保“快捷访问”排在最前)
    final_data = {}
    if "快捷访问" in data:
        final_data["快捷访问"] = data.pop("快捷访问")  # 先放快捷访问

    final_data.update(data)  # 再放其余分类

    print(f"🎉 解析成功：共整理出 {len(final_data)} 个分类。")

    return final_data


def generate_html(data):
    """根据解析到的数据生成最终的 HTML"""
    nav_html = ""
    content_html = ""

    for idx, (category, links) in enumerate(data.items()):
        if not links: continue

        cat_id = f"cat-{idx}"
        nav_html += f'<a href="#{cat_id}" class="nav-link">{category}</a>\n'

        content_html += f'''
        <div id="{cat_id}" class="category">
            <div class="cat-head">{category} <span style="font-size:12px;color:#999">({len(links)})</span></div>
            <div class="grid">
        '''

        for link in links:
            content_html += f'''
                <a href="{link['url']}" target="_blank" class="card" title="{link['title']}">
                    <img src="{link['icon']}" class="card-icon" loading="lazy" onerror="this.src='https://ui-avatars.com/api/?background=random&name={link['title'][0] if link['title'] else 'X'}'">
                    <div class="card-info">
                        <div class="card-text">{link['title']}</div>
                        <div class="card-url">{link['url']}</div>
                    </div>
                </a>
            '''
        content_html += '</div></div>\n'

    # 组合最终HTML (使用你的完整 HTML_HEADER 替换占位符)
    final_html = HTML_HEADER
    final_html = final_html.replace(
        '<div class="nav-scroll" id="nav-container"></div>',
        f'<div class="nav-scroll" id="nav-container">\n{nav_html}</div>')
    final_html = final_html.replace('<div id="content-container"></div>',
                                    f'<div id="content-container">\n{content_html}</div>')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(final_html)
    print(f"🚀 网页文件 {OUTPUT_FILE} 已生成！")


if __name__ == '__main__':
    try:
        import lxml

        bookmarks_data = parse_bookmarks()
        if bookmarks_data:
            generate_html(bookmarks_data)
        else:
            print(
                "❌ 致命错误：解析失败，生成的 index.html 可能是空的。请检查文件和 lxml 安装情况。")
    except ImportError:
        print(
            "⚠️ 缺少 lxml 库！这是解决解析问题的关键。请务必运行: pip install lxml")
        sys.exit(1)  # 强制退出，提醒用户安装
    except Exception as e:
        print(f"❌ 发生致命错误: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)